### ISSUE TITLE
ファイル名の大文字小文字による衝突の問題

### ISSUE THREAD

**Issue by Rokurolize** [Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP#47]
プロジェクトをクローンした際に、次のファイルが大文字小文字の違いによって衝突していることに気づきました。

1. 'template/ja_JP/extensions/Unprompted.json' と 'template/ja_JP/extensions/unprompted.json'
1. 'template/source/extensions/Hypernetwork-MonkeyPatch-Extension.json' と 'template/source/extensions/Hypernetwork-Monkeypatch-Extension.json'

これらの衝突は、大文字小文字を区別しないファイルシステム（例：Windows）で問題を引き起こします。両方のファイルのどちらか一方しかワーキングツリーに作成されません。

この問題を解決するために、以下の対応が必要かと思われます：

1. 衝突しているファイルを適切にマージします。
1. 大文字小文字の違いによる衝突が起こらないように、今後リポジトリに新しいファイルを追加する際に注意してください。

私の方でマージしてみてPRを投げる予定です。

**Comment by Katsuyuki-Karasawa** [comment]
2に関して、ソースは自分ではないのでコチラに投げられても困るとしか言えません
必要であれば[source](https://github.com/harukaxxxx/stable-diffusion-webui-localization-source)に沿って変更します

**Comment by Rokurolize** [comment]
> 必要であれば[source](https://github.com/harukaxxxx/stable-diffusion-webui-localization-source)に沿って変更します

教えていただいたリンク先を確認したところ、
https://github.com/harukaxxxx/stable-diffusion-webui-localization-source/commit/958c4db606bc609a3c95f808f8c53524daba06ce#diff-d8c973c298b896137a3d0dcd4315f8b33e1a28770c4ebe9b901943a314855512
の時点でファイル内容の更新およびファイル名の変更があったようです。

現在リンク先のリポジトリで衝突が発生しているわけではないので、普通にマージを進めようと思います。

**Comment by Katsuyuki-Karasawa** [comment]
ソース取得の自動化による影響で、途中でファイル名が変わっていたことに気が付かず、pushしていたのがおそらく原因でした
https://github.com/Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP/pull/49で解消していると思います
ご確認いただけますと幸いです

**Comment by Rokurolize** [comment]
2に関して解決しているのを確認しました。ご連絡ありがとうございます。

**Comment by harukaxxxx** [comment]
この度、大変なことになって本当に申し訳ございません。😣
この後、ソースファイルの命名規則は当拡張機能のリポジトリネームに従いますので、今後このような問題はもう出ませんと思います。
