### ISSUE TITLE
WebUIのWikiページを日本語に翻訳したい

### ISSUE THREAD

**Issue by Rokurolize** [Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP#62]
WebUIの使い方に関する日本語の情報はすでにいくつか提供されていますが、初心者の方々からの質問に対応していると、それらの日本語情報がメンテナンスされずに古くなり、結果として間違った操作を行ってエラーが発生するケースがしばしば見られました。

そこで、WebUIのリポジトリにあるWikiを日本語に翻訳し、手軽にアクセスできる信頼性のある情報源にしたいと考えています。

現在、Wikiはすでにこのリポジトリに複製されているようです。
https://github.com/Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP/wiki

Crowdinを活用して公式のWikiを翻訳プロジェクトに組み込むことは可能でしょうか？

**Comment by Katsuyuki-Karasawa** [comment]
できなくはないのですが、別のプロジェクトになるので少しCrowdin側の申請に時間がかかります
もともと少し考えていた手法があるのでそれを採用します
少々プラットフォームを整えてくるのでお待ちください

**Comment by Katsuyuki-Karasawa** [comment]
こちらについて少し保留とさせてください
理由は以下
1. まず、どちらかというと内容がDeveloper向け
    - これが最大の原因です
    - 基本的にここを読む層というのは開発者であり、また英語を翻訳をして捉えることができる層が多いので必要でないと感じる(自分がいい例です)
2. 基本的に更新するのがClashSANであり、この頃はあまり更新もされていない
3. markdownの翻訳のアプローチが厄介
    - Crowdinでもmarkdownの翻訳は可能ですが、あまりjsonやyamlなどと比べて形式が整っていない
    - 基本的に文章になるので単語単位よりもさらに訳し方に関して人を選ぶ
4. 1に関連して、もしターゲット層を一般ユーザーまで含めるのであればフロントエンドの用意が必要であるが、これのメンテナンスコストも視野に入れなくてはならない
    - 恥ずかしながら、自分の過去のリポジトリをいくつか見ていただくとわかりますが、mkdocsやDocusaurusのSSGのwikiのようなものを作ろうとしたことがありますが、基本的にメンテコストが高いです
    - ja_JP翻訳の人に対して、github側のコントリビュータが少ないのは必然ですが、このあたりの保守コストも考えていく必要があります

以上理由になります
以下のリポジトリの更新をそのうち行おうとは考えていますが、その際に人が増えてきたら考えるかもしれないくらいに思っていただけると幸いです
https://github.com/Katsuyuki-Karasawa/GenerativeAI-wiki

ちなみに、このrepo.wikiに関しては少し試験的に行おうとした結果の負の遺産に近しいもの(以上の理由から断念したもの)ですので、やはり個人的にはモチベーション維持ができないと思っています

**Comment by Rokurolize** [comment]
なるほど、承知しました。ご説明いただきありがとうございます。

Twitterで日本語化のことが拡散されてCrowdinのプロジェクトに参加してくれた人が何十人も集まったので、この勢いなら他の重要そうなドキュメントもサブのプロジェクトみたいな感じで動かせるかと思ったのですが、確かに管理の負担が凄そうですね。浅慮でした。

**Comment by Katsuyuki-Karasawa** [comment]
closeします
