### ISSUE TITLE
進捗のところを直す

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP#71]
https://github.com/Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP/commit/c30afc5999bf96a21d3503d7b559bad37e1898c8

この変更でCIがなんか変になったので直す

**Comment by Katsuyuki-Karasawa** [comment]
原因がわからん

**Comment by Katsuyuki-Karasawa** [comment]
取得できてるけど、Pushでなんか起こってる?

**Comment by Katsuyuki-Karasawa** [comment]
workflow_dispatchだと通った
どういうことだコレ

**Comment by Katsuyuki-Karasawa** [comment]
@yuuki76 これ以外にはとくに関連する部分変更加えてないですよね?

**Comment by Katsuyuki-Karasawa** [comment]
次マージしてこのActionsが回ったときになにも発生しなかったらcloseします

**Comment by yuuki76** [comment]
何もしてませんけど、例のGitHubのSSHのホスト鍵(RSA)が変更になった事案が関係してそう

**Comment by Katsuyuki-Karasawa** [comment]
もしかして同時に起動したActionsが干渉している...?

**Comment by Katsuyuki-Karasawa** [comment]
これが原因だったので統合しました。
