### ISSUE TITLE
同梱のBilingual Localizationが動かない

### ISSUE THREAD

**Issue by 9-w-9** [Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP#84]
2023年3月31日のコミット [add submodule](https://github.com/Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP/commit/66543bc4e627de510cdb4c8abfd7b7d6b5e968e2)以降、Bilingual Localizationが機能していないと思われます。
Settingsタブ - Bilingual Localization が表示されなくなり、それによる翻訳も行われなくなります。

応急処置として、stable-diffusion-webui-auto-translate-language拡張機能を別途導入して動かすことは可能でした。

**Comment by Katsuyuki-Karasawa** [comment]
こちらに記述するのを忘れていました
Twitterに記載していますが、webui側にsubmoduleで動作するcommitが入りました。
そのため、そちらに変更しています
https://twitter.com/Ktsyk_Krsw/status/1641618048204570626
